-- SSD: Add Subcontractors Table & Supplier PID system
-- Run this in Supabase SQL editor

-- 1. Add PID column to suppliers (if not already there)
ALTER TABLE public.suppliers 
ADD COLUMN IF NOT EXISTS "pid" TEXT UNIQUE;

-- 2. Create Subcontractors table
CREATE TABLE IF NOT EXISTS public.subcontractors (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "pid" TEXT UNIQUE NOT NULL,
    "fullName" TEXT NOT NULL,
    "company" TEXT,
    "specialty" TEXT,
    "phone" TEXT,
    "phone2" TEXT,
    "email" TEXT,
    "address" TEXT,
    "nic_passport" TEXT,
    "notes" TEXT,
    "status" TEXT DEFAULT 'Active',
    "createdAt" TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    "updatedAt" TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 3. Disable RLS on subcontractors for now (like other tables)
ALTER TABLE public.subcontractors DISABLE ROW LEVEL SECURITY;

-- 4. Add client_id column to projects (the linking column)
-- This enables filtering projects by client
ALTER TABLE public.projects 
ADD COLUMN IF NOT EXISTS "client_id" UUID REFERENCES public.clients(id) ON DELETE SET NULL;

CREATE INDEX IF NOT EXISTS idx_projects_client_id ON public.projects("client_id");

-- 5. Backfill: Try to match existing project.client text to clients.fullName
UPDATE public.projects p
SET "client_id" = c.id
FROM public.clients c
WHERE LOWER(p.client) = LOWER(c."fullName")
AND p."client_id" IS NULL;
