const fs = require('fs');

const schema = `
-- Drop existing tables if they exist to wipe the database
DROP TABLE IF EXISTS "public"."bankAccounts" CASCADE;
DROP TABLE IF EXISTS "public"."workRates" CASCADE;
DROP TABLE IF EXISTS "public"."workerRates" CASCADE;
DROP TABLE IF EXISTS "public"."suppliers" CASCADE;
DROP TABLE IF EXISTS "public"."advances" CASCADE;
DROP TABLE IF EXISTS "public"."advanceApplications" CASCADE;
DROP TABLE IF EXISTS "public"."cashSettlements" CASCADE;
DROP TABLE IF EXISTS "public"."obligationLines" CASCADE;
DROP TABLE IF EXISTS "public"."obligationHeaders" CASCADE;
DROP TABLE IF EXISTS "public"."attendances" CASCADE;
DROP TABLE IF EXISTS "public"."boqItems" CASCADE;
DROP TABLE IF EXISTS "public"."boqs" CASCADE;
DROP TABLE IF EXISTS "public"."settlements" CASCADE;
DROP TABLE IF EXISTS "public"."paymentLines" CASCADE;
DROP TABLE IF EXISTS "public"."paymentHeaders" CASCADE;
DROP TABLE IF EXISTS "public"."payments" CASCADE;
DROP TABLE IF EXISTS "public"."projectMaterials" CASCADE;
DROP TABLE IF EXISTS "public"."projectWorkers" CASCADE;
DROP TABLE IF EXISTS "public"."materials" CASCADE;
DROP TABLE IF EXISTS "public"."workers" CASCADE;
DROP TABLE IF EXISTS "public"."projects" CASCADE;

-- Create Projects Table
CREATE TABLE public.projects (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" TEXT NOT NULL,
    "status" TEXT,
    "startDate" TEXT,
    "endDate" TEXT,
    "budget" NUMERIC,
    "amount" NUMERIC,
    "received" NUMERIC,
    "remaining" NUMERIC,
    "client" TEXT,
    "clientContact" TEXT,
    "clientPhone" TEXT,
    "location" TEXT,
    "contractValue" NUMERIC,
    "projectType" TEXT,
    "progress" INTEGER,
    "description" TEXT,
    "notes" TEXT,
    "createdAt" TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Create Workers Table
CREATE TABLE public.workers (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "fullName" TEXT NOT NULL,
    "role" TEXT,
    "dailyRate" NUMERIC,
    "hourlyRate" NUMERIC,
    "otRate" NUMERIC,
    "weeklyAllowance" NUMERIC,
    "phone" TEXT,
    "phone2" TEXT,
    "nic" TEXT,
    "address" TEXT,
    "baseWeekly" NUMERIC,
    "status" TEXT DEFAULT 'Active',
    "notes" TEXT,
    "createdAt" TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Create Materials Table
CREATE TABLE public.materials (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" TEXT NOT NULL,
    "category" TEXT,
    "unit" TEXT,
    "cost" NUMERIC,
    "quantity" NUMERIC DEFAULT 0,
    "minStock" NUMERIC DEFAULT 0,
    "supplierId" BIGINT,
    "description" TEXT,
    "notes" TEXT,
    "createdAt" TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Create ProjectWorkers Mapping Table
CREATE TABLE public."projectWorkers" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "projectId" BIGINT REFERENCES public.projects(id) ON DELETE CASCADE,
    "workerId" BIGINT REFERENCES public.workers(id) ON DELETE CASCADE,
    "assignedFrom" TEXT,
    "assignedTo" TEXT,
    "role" TEXT,
    "notes" TEXT,
    "createdAt" TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Create ProjectMaterials Mapping Table
CREATE TABLE public."projectMaterials" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "projectId" BIGINT REFERENCES public.projects(id) ON DELETE CASCADE,
    "materialId" BIGINT REFERENCES public.materials(id) ON DELETE CASCADE,
    "quantity" NUMERIC,
    "date" TEXT,
    "notes" TEXT,
    "createdAt" TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Create Payments Table
CREATE TABLE public.payments (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "projectId" BIGINT REFERENCES public.projects(id) ON DELETE SET NULL,
    "date" TEXT NOT NULL,
    "category" TEXT,
    "notes" TEXT,
    "amount" NUMERIC NOT NULL,
    "method" TEXT,
    "status" TEXT,
    "reference" TEXT,
    "direction" TEXT,
    "workerId" BIGINT REFERENCES public.workers(id) ON DELETE SET NULL,
    "supplierId" BIGINT,
    "materialId" BIGINT REFERENCES public.materials(id) ON DELETE SET NULL,
    "quantity" NUMERIC,
    "createdAt" TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Create PaymentHeaders Table
CREATE TABLE public."paymentHeaders" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "workerId" BIGINT REFERENCES public.workers(id) ON DELETE CASCADE,
    "periodStart" TEXT,
    "periodEnd" TEXT,
    "totalEarned" NUMERIC,
    "totalAdvance" NUMERIC,
    "netPayable" NUMERIC,
    "paidAmount" NUMERIC,
    "status" TEXT,
    "createdAt" TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Create PaymentLines Table
CREATE TABLE public."paymentLines" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "headerId" BIGINT REFERENCES public."paymentHeaders"(id) ON DELETE CASCADE,
    "date" TEXT,
    "projectId" BIGINT REFERENCES public.projects(id) ON DELETE SET NULL,
    "hoursWorked" NUMERIC,
    "rate" NUMERIC,
    "lineTotal" NUMERIC,
    "createdAt" TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Create Settlements Table
CREATE TABLE public.settlements (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "headerId" BIGINT REFERENCES public."paymentHeaders"(id) ON DELETE CASCADE,
    "date" TEXT,
    "amount" NUMERIC,
    "method" TEXT,
    "reference" TEXT,
    "createdAt" TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Create BOQs Table
CREATE TABLE public.boqs (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "projectId" BIGINT REFERENCES public.projects(id) ON DELETE CASCADE,
    "title" TEXT NOT NULL,
    "toAddress" TEXT,
    "notes" TEXT,
    "documentDate" TEXT,
    "createdAt" TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Create BOQItems Table
CREATE TABLE public."boqItems" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "boqId" BIGINT REFERENCES public.boqs(id) ON DELETE CASCADE,
    "itemNo" TEXT,
    "description" TEXT,
    "quantity" NUMERIC,
    "unit" TEXT,
    "rate" NUMERIC,
    "amount" NUMERIC,
    "createdAt" TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Create Attendances Table
CREATE TABLE public.attendances (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "workerId" BIGINT REFERENCES public.workers(id) ON DELETE CASCADE,
    "date" TEXT NOT NULL,
    "status" TEXT,
    "isPresent" BOOLEAN,
    "isHalfDay" BOOLEAN,
    "hoursWorked" NUMERIC,
    "hours" NUMERIC, -- Kept for app compatibility
    "projectId" BIGINT REFERENCES public.projects(id) ON DELETE SET NULL,
    "createdAt" TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Create ObligationHeaders Table
CREATE TABLE public."obligationHeaders" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "type" TEXT,
    "direction" TEXT,
    "entityType" TEXT,
    "entityId" BIGINT,
    "clientName" TEXT,
    "supplierId" BIGINT,
    "projectId" BIGINT REFERENCES public.projects(id) ON DELETE SET NULL,
    "totalAmountSnapshot" NUMERIC,
    "dueDate" TEXT,
    "status" TEXT,
    "notes" TEXT,
    "createdAt" TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Create ObligationLines Table
CREATE TABLE public."obligationLines" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "headerId" BIGINT REFERENCES public."obligationHeaders"(id) ON DELETE CASCADE,
    "materialId" BIGINT REFERENCES public.materials(id) ON DELETE SET NULL,
    "description" TEXT,
    "quantity" NUMERIC,
    "unitPrice" NUMERIC,
    "lineTotal" NUMERIC,
    "createdAt" TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Create CashSettlements Table
CREATE TABLE public."cashSettlements" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "obligationHeaderId" BIGINT REFERENCES public."obligationHeaders"(id) ON DELETE CASCADE,
    "date" TEXT,
    "amount" NUMERIC,
    "direction" TEXT,
    "method" TEXT,
    "reference" TEXT,
    "createdAt" TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Create AdvanceApplications Table
CREATE TABLE public."advanceApplications" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "workerId" BIGINT REFERENCES public.workers(id) ON DELETE CASCADE,
    "date" TEXT,
    "amountRequested" NUMERIC,
    "reason" TEXT,
    "status" TEXT,
    "approvedAmount" NUMERIC,
    "createdAt" TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Create Advances Table
CREATE TABLE public.advances (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "workerId" BIGINT REFERENCES public.workers(id) ON DELETE CASCADE,
    "projectId" BIGINT REFERENCES public.projects(id) ON DELETE SET NULL,
    "date" TEXT,
    "amount" NUMERIC,
    "notes" TEXT, -- Changed from reason
    "status" TEXT,
    "createdAt" TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Create Suppliers Table
CREATE TABLE public.suppliers (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" TEXT NOT NULL,
    "contact" TEXT,
    "email" TEXT,
    "address" TEXT,
    "notes" TEXT,
    "isActive" BOOLEAN DEFAULT TRUE,
    "category" TEXT,
    "bankDetails" TEXT,
    "createdAt" TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Add ForeignKey for Payment to Supplier now that Suppliers exists
ALTER TABLE public.payments ADD CONSTRAINT "payments_supplierId_fkey" FOREIGN KEY ("supplierId") REFERENCES public.suppliers(id) ON DELETE SET NULL;
ALTER TABLE public."obligationHeaders" ADD CONSTRAINT "obligationHeaders_supplierId_fkey" FOREIGN KEY ("supplierId") REFERENCES public.suppliers(id) ON DELETE SET NULL;

-- Create WorkerRates Table
CREATE TABLE public."workerRates" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "role" TEXT NOT NULL,
    "hourlyRate" NUMERIC,
    "dailyRate" NUMERIC,
    "overtimeRate" NUMERIC,
    "createdAt" TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Create WorkRates Table
CREATE TABLE public."workRates" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "category" TEXT NOT NULL,
    "name" TEXT,
    "unit" TEXT,
    "ratePerUnit" NUMERIC, -- Changed from rate
    "description" TEXT,
    "createdAt" TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Create BankAccounts Table
CREATE TABLE public."bankAccounts" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "entityType" TEXT NOT NULL,
    "entityId" TEXT NOT NULL,
    "name" TEXT,
    "accName" TEXT,
    "accNo" TEXT,
    "bank" TEXT,
    "branch" TEXT,
    "createdAt" TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Disable Row Level Security on all tables just in case Supabase re-enables them
ALTER TABLE "bankAccounts" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "workRates" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "workerRates" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "suppliers" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "advances" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "advanceApplications" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "cashSettlements" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "obligationLines" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "obligationHeaders" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "attendances" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "boqItems" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "boqs" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "settlements" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "paymentLines" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "paymentHeaders" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "payments" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "projectMaterials" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "projectWorkers" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "materials" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "workers" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "projects" DISABLE ROW LEVEL SECURITY;
`;

fs.writeFileSync('schema.sql', schema);
console.log('schema.sql generated successfully. All columns explicitly quoted.');
