-- Phase 1: Database Foundation for Multi-Tiered Roles (Safe, Additive)

-- 1. Create the user_roles table
CREATE TABLE IF NOT EXISTS public.user_roles (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "user_id" UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    "role" TEXT NOT NULL CHECK (role IN (
        'super_admin', 
        'project_manager', 
        'site_supervisor', 
        'finance', 
        'supplier', 
        'sub_contractor', 
        'worker', 
        'client'
    )),
    "createdAt" TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    CONSTRAINT "unique_user_role" UNIQUE ("user_id")
);

-- Enable RLS on user_roles 
ALTER TABLE public.user_roles ENABLE ROW LEVEL SECURITY;

-- Allow users to read only their own role
DROP POLICY IF EXISTS "Users can read own role" ON public.user_roles;
CREATE POLICY "Users can read own role"
    ON public.user_roles
    FOR SELECT
    USING (auth.uid() = user_id);

-- 2. Create a secure Supabase function to get the current user's role
-- This is SECURITY DEFINER so it can bypass RLS just for this specific secure check.
CREATE OR REPLACE FUNCTION public.get_user_role()
RETURNS TEXT
LANGUAGE sql
SECURITY DEFINER 
AS $$
    SELECT role FROM public.user_roles WHERE user_id = auth.uid() LIMIT 1;
$$;
